export const ReviewsCaruselData = [
  {
    id: 1,
    srcimg: "/images/testimonials/reviews-carusel__img01.jpg",
    title: `What People Say About Us`,
    subtitle: `testimonials`,
    text: `Super impressed with the team's professionalism and prompt service. Our gas heater was up and running again in no time, and the pricing was very fair. Highly recommend these guys for anyone needing reliable gas heating repairs in Melbourne!`,
    signature__title: "Ben Thompson",
    signature__text: "Homeowner",
    stars: 5,
    youtubeVideoCode: "wHPqgzlRasA",
  },
  {
    id: 2,
    srcimg: "/images/testimonials/reviews-carusel__img01.jpg",
    title: `What People Say About Us`,
    subtitle: `testimonials`,
    text: `The technician explained everything clearly and made sure our heater was safe and working efficiently. Excellent customer care from start to finish. Wouldn't go anywhere else for gas heating services`,
    signature__title: "Liam O'Connor",
    signature__text: "Property Manager",
    stars: 5,
    youtubeVideoCode: "wHPqgzlRasA",
  },
  {
    id: 3,
    srcimg: "/images/testimonials/reviews-carusel__img01.jpg",
    title: `What People Say About Us`,
    subtitle: `testimonials`,
    text: `Outstanding emergency service! Called them late at night when our gas heater broke down, and they had someone out within 2 hours. Professional, knowledgeable, and reasonably priced. Will definitely use them again.`,
    signature__title: "Sarah Mitchell",
    signature__text: "Supervisor",
    stars: 5,
    youtubeVideoCode: "wHPqgzlRasA",
  },
  {
    id: 4,
    srcimg: "/images/testimonials/reviews-carusel__img01.jpg",
    title: `What People Say About Us`,
    subtitle: `testimonials`,
    text: `Had them install a new Rinnai heater in our Doncaster home. The installers were clean, efficient, and left everything in perfect condition. Very happy with the workmanship and the gas heating system is running beautifully now.`,
    signature__title: "James Patterson",
    signature__text: "Homeowner",
    stars: 5,
    youtubeVideoCode: "wHPqgzlRasA",
  },
  {
    id: 5,
    srcimg: "/images/testimonials/reviews-carusel__img01.jpg",
    title: `What People Say About Us`,
    subtitle: `testimonials`,
    text: `We had a gas leak scare in our Frankston property. These guys responded within the hour, diagnosed the issue professionally, and fixed it safely. Put my mind at ease completely. Their expertise in safety is top-notch.`,
    signature__title: "Michelle Adams",
    signature__text: "Homeowner",
    stars: 5,
    youtubeVideoCode: "wHPqgzlRasA",
  },
  {
    id: 6,
    srcimg: "/images/testimonials/reviews-carusel__img01.jpg",
    title: `What People Say About Us`,
    subtitle: `testimonials`,
    text: `Annual servicing of our commercial heating system. They're punctual, thorough, and provide detailed reports. Our building stays warm through the winter and we haven't had a single breakdown. Great value for ongoing maintenance.`,
    signature__title: "David Chen",
    signature__text: "Facilities Manager",
    stars: 4,
    youtubeVideoCode: "wHPqgzlRasA",
  },
  {
    id: 7,
    srcimg: "/images/testimonials/reviews-carusel__img01.jpg",
    title: `What People Say About Us`,
    subtitle: `testimonials`,
    text: `Booked them for carbon monoxide testing after getting our heater serviced. The technician was thorough and explained the safety procedures well. It's reassuring to know our home is safe. Definitely recommend their safety-focused approach.`,
    signature__title: "Rebecca Walsh",
    signature__text: "Homeowner",
    stars: 5,
    youtubeVideoCode: "wHPqgzlRasA",
  },
  {
    id: 8,
    srcimg: "/images/testimonials/reviews-carusel__img01.jpg",
    title: `What People Say About Us`,
    subtitle: `testimonials`,
    text: `Replaced our old Brivis heater before winter. The team was professional, kept everything tidy, and answered all my questions. The new system is quiet and efficient. Best investment we made for our home comfort.`,
    signature__title: "Christopher Brown",
    signature__text: "Homeowner",
    stars: 5,
    youtubeVideoCode: "wHPqgzlRasA",
  },
  {
    id: 9,
    srcimg: "/images/testimonials/reviews-carusel__img01.jpg",
    title: `What People Say About Us`,
    subtitle: `testimonials`,
    text: `Emergency call-out on a freezing winter's night. They got to our Caulfield place quickly, identified the problem immediately, and had us heated within 45 minutes. Professional, friendly, and honest pricing. Lifesavers!`,
    signature__title: "Nicole Rodriguez",
    signature__text: "Homeowner",
    stars: 5,
    youtubeVideoCode: "wHPqgzlRasA",
  },
  {
    id: 10,
    srcimg: "/images/testimonials/reviews-carusel__img01.jpg",
    title: `What People Say About Us`,
    subtitle: `testimonials`,
    text: `Regular maintenance visits for our retail space in the CBD. They always find small issues before they become big problems. The preventative approach saves us money and keeps customers comfortable. Excellent ongoing support.`,
    signature__title: "Andrew Stewart",
    signature__text: "Business Owner",
    stars: 4,
    youtubeVideoCode: "wHPqgzlRasA",
  },
  {
    id: 11,
    srcimg: "/images/testimonials/reviews-carusel__img01.jpg",
    title: `What People Say About Us`,
    subtitle: `testimonials`,
    text: `Fantastic gas heater installation from start to finish. The team arrived on time, explained the options suited to our home size, and installed a ducted system in under a day. Warm, cosy winter ever since — couldn't ask for more!`,
    signature__title: "Olivia Hartmann",
    signature__text: "Homeowner – Glen Waverley",
    stars: 5,
    youtubeVideoCode: "wHPqgzlRasA",
  },
];
