export const ReviewsCaruselData = [
  {
    id: 1,
    srcimg: "/images/testimonials/reviews-carusel__img01.jpg",
    title: `What People Say About Us`,
    subtitle: `testimonials`,
    text: `Super impressed with the team's professionalism and prompt service. Our gas heater was up and running again in no time, and the pricing was very fair. Highly recommend these guys for anyone needing reliable gas heating repairs in Melbourne!`,
    signature__title: "Ben Thompson",
    signature__text: "Supervisor",
    stars: 5,
    youtubeVideoCode: "wHPqgzlRasA",
  },
  {
    id: 2,
    srcimg: "/images/testimonials/reviews-carusel__img01.jpg",
    title: `What People Say About Us`,
    subtitle: `testimonials`,
    text: `The technician explained everything clearly and made sure our heater was safe and working efficiently. Excellent customer care from start to finish. Wouldn't go anywhere else for gas heating services`,
    signature__title: "Liam O'Connor",
    signature__text: "Homeowner",
    stars: 4,
    youtubeVideoCode: "wHPqgzlRasA",
  },
  {
    id: 3,
    srcimg: "/images/testimonials/reviews-carusel__img01.jpg",
    title: `What People Say About Us`,
    subtitle: `testimonials`,
    text: `Outstanding emergency service! Called them late at night when our gas heater broke down, and they had someone out within 2 hours. Professional, knowledgeable, and reasonably priced. Will definitely use them again.`,
    signature__title: "Sarah Mitchell",
    signature__text: "Property Manager",
    stars: 5,
    youtubeVideoCode: "wHPqgzlRasA",
  },
];
